spring:
  application:
    name: project-atlas

  datasource:
    url: ${DB_URL:jdbc:mysql://root:jRhRjRLEkMKxFUCWRqLAOtJEaWMqfoqs@mysql.railway.internal:3306/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:jRhRjRLEkMKxFUCWRqLAOtJEaWMqfoqs}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: false

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/seed-data.sql

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.projectatlas: DEBUG
